# Generated by Django 4.2.1 on 2023-10-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kids",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("product_img", models.ImageField(upload_to="kid")),
            ],
        ),
    ]
