# Generated by Django 4.2.1 on 2023-11-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_busstop_bus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="departure_time",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="source",
        ),
        migrations.RemoveField(
            model_name="busstop",
            name="time_to_reach",
        ),
        migrations.CreateModel(
            name="BusStopRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("time_to_reach", models.TimeField()),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.bus"
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.busstop"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="bus",
            name="stops",
            field=models.ManyToManyField(
                through="app1.BusStopRelationship", to="app1.busstop"
            ),
        ),
    ]
