# Generated by Django 4.2.1 on 2023-11-07 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_bus_departure_time_remove_bus_destination_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="busstoprelationship",
            name="bus",
        ),
        migrations.RemoveField(
            model_name="busstoprelationship",
            name="stop",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="stops",
        ),
        migrations.AddField(
            model_name="bus",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="bus",
            name="dest_stops",
            field=models.TextField(default="default_value_here"),
        ),
        migrations.AddField(
            model_name="bus",
            name="source_stops",
            field=models.TextField(default="default_value_here"),
        ),
        migrations.DeleteModel(
            name="BusStop",
        ),
        migrations.DeleteModel(
            name="BusStopRelationship",
        ),
    ]
