# Generated by Django 4.2.1 on 2023-11-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_remove_busstoprelationship_bus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="date",
            field=models.DateField(
                verbose_name=models.DateTimeField(auto_now_add=True)
            ),
        ),
    ]
