# Generated by Django 4.2.1 on 2023-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_bus_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="date",
            field=models.DateTimeField(
                verbose_name=models.DateTimeField(auto_now_add=True)
            ),
        ),
    ]
