# Generated by Django 4.2.1 on 2023-11-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_alter_bus_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="bus",
            name="dest_stops",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="source_stops",
        ),
        migrations.AlterField(
            model_name="bus",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_to_reach", models.IntegerField()),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.bus"
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.stop"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bus",
            name="stops",
            field=models.ManyToManyField(
                related_name="buses", through="app1.BusStop", to="app1.stop"
            ),
        ),
    ]
