# Generated by Django 4.2.1 on 2023-11-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_stop_remove_bus_dest_stops_remove_bus_source_stops_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BusStop",
            new_name="BusStops",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="date",
        ),
    ]
