# Generated by Django 4.2.1 on 2023-11-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_stop_bus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bus",
        ),
        migrations.DeleteModel(
            name="Stop",
        ),
    ]
