# Generated by Django 4.2.1 on 2023-11-14 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_bus_stop_busstoproute_bus_stops"),
    ]

    operations = [
        migrations.AddField(
            model_name="busstoproute",
            name="departure_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
