# Generated by Django 4.2.1 on 2023-11-15 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_bus_bus_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardingstop",
            name="departure_time",
            field=models.DateTimeField(default=datetime.date(2023, 11, 22)),
        ),
        migrations.AlterField(
            model_name="destinationstop",
            name="arrival_time",
            field=models.DateTimeField(default=datetime.date(2023, 11, 22)),
        ),
    ]
