# Generated by Django 4.2.1 on 2023-11-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_alter_boardingstop_departure_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardingstop",
            name="departure_time",
            field=models.TimeField(default=20),
        ),
        migrations.AlterField(
            model_name="destinationstop",
            name="arrival_time",
            field=models.TimeField(default=8),
        ),
    ]
