# Generated by Django 4.2.1 on 2023-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_alter_boardingstop_departure_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingstop",
            name="distance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="destinationstop",
            name="distance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
