# Generated by Django 4.2.1 on 2023-11-22 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0020_alter_bus_bus_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookedSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                ("booking_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booked_seats",
                        to="app1.bus",
                    ),
                ),
            ],
        ),
    ]
