# Generated by Django 4.2.1 on 2023-11-23 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0021_bookedseat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookedseat",
            name="booking_date",
        ),
        migrations.RemoveField(
            model_name="bookedseat",
            name="bus",
        ),
        migrations.AddField(
            model_name="bookedseat",
            name="bus_id",
            field=models.CharField(default="YourDefaultValueHere", max_length=100),
        ),
        migrations.AddField(
            model_name="bookedseat",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="bookedseat",
            name="passenger_gender",
            field=models.CharField(default="Unknown", max_length=10),
        ),
        migrations.AddField(
            model_name="bookedseat",
            name="passenger_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
