# Generated by Django 4.2.1 on 2023-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0022_remove_bookedseat_booking_date_remove_bookedseat_bus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedseat",
            name="status",
            field=models.CharField(default="unknown", max_length=10),
        ),
    ]
