# Generated by Django 4.2.1 on 2023-11-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0023_bookedseat_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedseat",
            name="bus_name",
            field=models.CharField(default="YourDefaultValueHere", max_length=100),
        ),
    ]
