# Generated by Django 4.2.1 on 2023-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0025_bookedseat_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardingstop",
            name="departure_time",
            field=models.TimeField(default="20:00"),
        ),
        migrations.AlterField(
            model_name="destinationstop",
            name="arrival_time",
            field=models.TimeField(default="08:00"),
        ),
    ]
