# Generated by Django 4.2.1 on 2023-07-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="items_img",
            field=models.ImageField(null=True, upload_to="products"),
        ),
    ]
